e-line-websolutions/mustang-shared

services/webmanager.cfc

Last item in path can be both an article or a menu item

Changed SEO path end-point to article

---

mustang.cfc
services/queryService.cfc
services/utility.cfc

- threadfix
- mergeStructs
- variableFormat
- queryService

webmanager bugfixes

---

services/data.cfc
services/utility.cfc
services/webmanager.cfc

Added 'ALL' to replace in variableFormat function in utility service
Added some flexibilty to the queryToTree function in data service
Added a getNavigation function to webmanager service

Changes to the data, utility and webmanager services

---

services/data.cfc

- added null support
- fixed a bug with arrays
- added case insensitive support

A few bug fixes for xmlFromStruct()

---

services/webmanager.cfc

Added search function and a path from id function

Search and pathfromid

---

services/imageScaler.cfc
services/webmanager.cfc

Also, some cache/speed improvements

Added byline to webmanager images

---

mustang.cfc
services/utility.cfc
webmanager.cfc

added optional html page for when an error occurs and catching potential
errors inside the error handler

improved error handling

---

services/asyncQueue.cfc
services/log.cfc
services/option.cfc
services/queryService.cfc

temporarily disabled dumpToFile() because it caused the FTS import to
crash

fixes for bugs encountered while working on fts

---

services/log.cfc
services/utility.cfc
tests/specs/json.cfc
tests/specs/log.cfc
tests/specs/utility.cfc
tests/specs/webmanager.cfc

Added Mark Mandel's amInCFThread() function to test for nested threads

Fixed a bug with writing a cfdump to a file in the logService

---

mustang.cfc

This replaces the nuke option, so that can be used just to nuke the
database in future projects

Added clear URL variable to clear caches

---

services/webmanager.cfc

Exclude all files of resizing before serving except jpg, jpeg, png and
gif

Addition to serving media

---

services/data.cfc
services/log.cfc

used by the logService so it doesn't crash on logging ORM entities

added deOrm to dataService

---

base.cfc
webmanager.cfc

getting a bit desperate, trying to fix a very vague bug where de
application suddenly loses some keys in de global config struct

Renamed an argument

---

mustang.cfc
services/data.cfc
services/log.cfc
services/security.cfc

- HBMXML files are now generated and moved to the documentation dir,
then removed from the model on `nuke`.
- Some minor cosmetic fixes to securityService and logService

Added keyValuePairFind to dataService

---

controllers/crud.cfc
webmanager.cfc

- added stack trace to debug API calls
- included array of subclasses to columns in CRUD controller

Spruced up the error reporting for webmanager sites

---

controllers/crud.cfc

Add `useForViews="your-view-here"` to the super class attributes to tell
Mustang which view to use for all child components

Added way to use super class as view indicator

---

controllers/crud.cfc
lib/rollbar/Rollbar.cfc
services/crud.cfc
services/data.cfc
services/log.cfc
services/utility.cfc
tests/specs/data.cfc

- added strict mode to isGUID
- fixed bug with threading in logService
- cleanup on crudService

Bug fixes and 1 feature

---

controllers/crud.cfc
controllers/security.cfc
services/asyncQueue.cfc
services/data.cfc
services/log.cfc
services/progress.cfc
services/threaded.cfc
services/utility.cfc

- Add way to output progressService status messages directly to buffer
- Fix rollbar error when missing access token
- Fix async single threaded run
- Fix logging bug in securityService
- Add way to run functions of a superclass controller (used for
inheriting beans that have a view assigned to them through the
superclass)

Lots of fixes to do with a major cava/basecfc update

---

services/email.cfc
services/utility.cfc

New function to check email validity, CF9's isValid('email') doest not
cover all TLDs

Validemailbranch

---

services/email.cfc

Added possibility to add attachements to emails

Email attachement

---

services/email.cfc

Added possibility to have multiple to and from addresses

Multiple to and from addresses

---

services/webmanager.cfc

Making the getMenuIdFromPath function public to use in JFR

Private to public

---

base.cfc
services/file.cfc
services/jsonJava.cfc
services/log.cfc
services/option.cfc
services/webmanager.cfc

add method: redirectToMainUrl
add method: jsonFileToCf
add method: getFileLastModified
add locking to cacheget/put for config file

Small tweaks

---

base.cfc
documentation/mustang-start/config/localhost.json
documentation/mustang-start/config/mustang-test.mjh.json
documentation/mustang-start/webroot/Application.cfc
documentation/mustang-start/webroot/web.config
services/asyncQueue.cfc
services/file.cfc
services/queryService.cfc
services/utility.cfc

Cleaned up a few things, added some cache expiration timers and improved debug output.

 Minor improvements

---

services/oauth.cfc

added possibility to store multiple oauth tokens by addind an id

Allow multiple apps in oauth service

---

services/file.cfc
services/queryService.cfc

added getFileType to fileService
speed improvement in query service

minor update to file and query service

---

services/data.cfc

- return original array if sort fails on subkey missing
- dump errors to file if xmlSearch fails

small fixes for arrayOfStructsSort and xmlFilter

---

documentation/mustang-start/model/beans/permission.cfc

Made securityrole editable in edit screen

securityrole edit screen

---

controllers/security.cfc
services/email.cfc
services/webmanager.cfc

Making it possible to add more than 1 email attachement + minor fixes

Email attachements

---

config/global.json
services/data.cfc
services/webmanager.cfc
webmanager.cfc

also ran code formatter on webmanagerService

bunch of fixes done during busy time on server

---

base.cfc
mustang.cfc
services/queryService.cfc
services/webmanager.cfc
webmanager.cfc

Was previously a webmanager only feature.

Moved cache over to mustang base

---

base.cfc
controllers/security.cfc
mustang.cfc

- point specifically to mustang/base.cfc
- not tied to lucee, but support different html error templates based on errorCode

Some fixes for Lucee compatibility

---

controllers/security.cfc
services/security.cfc

report 401 error back to API users

Security Service fixes

---

services/data.cfc

sorts struct keys of both numeric and string values

add getSortedStructKeys

---

services/data.cfc

Added a function to return nested data inside an entity using a dotted path.
getByPath( entity, 'path.to.item', 'alternative' )

Add getByPath()

---

controllers/crud.cfc

save, delete and restore were still missing those features

Add dontRedirect and redirectTo options to CRUD controller

---

documentation/mustang-start/webroot/inc/js/admin.js
services/data.cfc

Fix: It should now return the actual values compared to `searchedOn`
Add: numericalCompare()

Trying to improve getByPath()

---

services/file.cfc

added to fileService, needed for cava/signhost

add getMimetypeFromBinaryFile() and encodeFileToBase64Binary()

---

controllers/profile.cfc
controllers/security.cfc

fix some issues and add custom url to another part of password retrieval

more pw customization

---

services/content.cfc

new arg: `contentTable`. Supported entitres are any that inherrit from `content`.

add support for different tables to getByFQA()

---

mustang.cfc

also, add try/catch and transaction blocks

Only execute nukescript on dropcreate

---

services/translation.cfc
services/utility.cfc

Useful for providing different translations per website

Add support for grouped language files

---

services/utility.cfc

Besides parsing #this#, it'll also parse {this}.

Add accolades as parsable variables

---

base.cfc
services/asyncQueue.cfc
services/debug.cfc
services/progress.cfc

also, some ACF compatibility issues

update relative paths support in config

---

base.cfc

Adding config files based on domain. We want to be able to make a config for all woningwaard websites for example instead of making a config file per subdomain

Domain config
